title: Jekyll tags and cats
description: Jekyll example about how to generate categories and tags pages.
twitter_username: ilanolkies
github_username:  ilanolkies
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  